// Codes from https://openweathermap.org/weather-conditions
export const conditionMetaInfo = {
  200: {
    main: "Tempestade",
    description: "thunderstorm with light rain",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  201: {
    main: "Tempestade",
    description: "thunderstorm with rain",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  202: {
    main: "Tempestade",
    description: "thunderstorm with heavy rain",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  210: {
    main: "Tempestade",
    description: "light thunderstorm",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  211: {
    main: "Tempestade",
    description: "Tempestade",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  212: {
    main: "Tempestade",
    description: "heavy thunderstorm",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  221: {
    main: "Tempestade",
    description: "ragged thunderstorm",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  230: {
    main: "Tempestade",
    description: "thunderstorm with light drizzle",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  231: {
    main: "Tempestade",
    description: "thunderstorm with drizzle",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  232: {
    main: "Tempestade",
    description: "thunderstorm with heavy drizzle",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },

  300: {
    main: "Chuvisco",
    description: "light intensity drizzle",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  301: {
    main: "Chuvisco",
    description: "Chuvisco",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  302: {
    main: "Chuvisco",
    description: "heavy intensity drizzle",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  310: {
    main: "Chuvisco",
    description: "light intensity drizzle rain",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  311: {
    main: "Chuvisco",
    description: "drizzle rain",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  312: {
    main: "Chuvisco",
    description: "heavy intensity drizzle rain",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  313: {
    main: "Chuvisco",
    description: "shower rain and drizzle",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  314: {
    main: "Chuvisco",
    description: "heavy shower rain and drizzle",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  321: {
    main: "Chuvisco",
    description: "shower drizzle",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },

  500: {
    main: "Chuva",
    description: "light rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  501: {
    main: "Chuva",
    description: "moderate rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  502: {
    main: "Chuva",
    description: "heavy intensity rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  503: {
    main: "Chuva",
    description: "very heavy rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  504: {
    main: "Chuva",
    description: "extreme rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  511: {
    main: "Chuva",
    description: "freezing rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  520: {
    main: "Chuva",
    description: "light intensity shower rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  521: {
    main: "Chuva",
    description: "shower rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  522: {
    main: "Chuva",
    description: "heavy intensity shower rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  531: {
    main: "Chuva",
    description: "ragged shower rain",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },

  600: {
    main: "Neve",
    description: "light snow",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  601: {
    main: "Neve",
    description: "Neve",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  602: {
    main: "Neve",
    description: "Heavy snow",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  611: {
    main: "Neve",
    description: "Sleet",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  612: {
    main: "Neve",
    description: "Light shower sleet",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  613: {
    main: "Neve",
    description: "Shower sleet",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  615: {
    main: "Neve",
    description: "Light rain and snow",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  616: {
    main: "Neve",
    description: "Rain and snow",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  620: {
    main: "Neve",
    description: "Light shower snow",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  621: {
    main: "Neve",
    description: "Shower snow",
    iconDay: "",
    iconNight: "",
  },
  622: {
    main: "Neve",
    description: "Heavy shower snow",
    iconDay: "",
    iconNight: "",
  },

  701: {
    main: "Nevoeiro",
    description: "Nevoeiro",
    iconDay: "wi-smog",
    iconNight: "wi-smog",
  },
  711: {
    main: "Fumaça",
    description: "Smoke",
    iconDay: "wi-smoke",
    iconNight: "wi-smoke",
  },
  721: {
    main: "Nevoeiro",
    description: "Haze",
    iconDay: "wi-day-haze",
    iconNight: "wi-day-haze",
  },
  731: {
    main: "Areia",
    description: "sand/ dust whirls",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  741: {
    main: "Neblina",
    description: "fog",
    iconDay: "wi-fog",
    iconNight: "wi-night-fog",
  },
  751: {
    main: "Areia",
    description: "sand",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  761: {
    main: "Areia",
    description: "dust",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  762: {
    main: "Ash",
    description: "volcanic ash",
    iconDay: "wi-volcano",
    iconNight: "wi-volcano",
  },
  771: {
    main: "Rajadas de vento",
    description: "squalls",
    iconDay: "wi-strong-wind",
    iconNight: "wi-strong-wind",
  },
  781: {
    main: "Tornado",
    description: "tornado",
    iconDay: "wi-tornado",
    iconNight: "wi-tornado",
  },

  800: {
    main: "Limpo",
    description: "céu limpo",
    iconDay: "wi-day-sunny",
    iconNight: "wi-night-clear",
  },
  801: {
    main: "Nuvens",
    description: "poucas nuvens",
    iconDay: "wi-day-cloudy",
    iconNight: "wi-night-alt-cloudy",
  },
  802: {
    main: "Nuvens esparças",
    description: "algumas nuvens",
    iconDay: "wi-day-cloudy",
    iconNight: "wi-night-alt-cloudy",
  },
  803: {
    main: "Parcialmente nublado",
    description: "muitas nuvens",
    iconDay: "wi-cloudy",
    iconNight: "wi-cloudy",
  },
  804: {
    main: "Nublado",
    description: "100% nublado",
    iconDay: "wi-cloudy",
    iconNight: "wi-cloudy",
  },
};
