// Codes from https://openweathermap.org/weather-conditions
export const conditionMetaInfo = {
  200: {
    main: "Tempestade",
    description: "Tempestade com chuva leve",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  201: {
    main: "Tempestade",
    description: "Tempestade com chuva",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  202: {
    main: "Tempestade",
    description: "Tempestade com chuva forte",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  210: {
    main: "Tempestade",
    description: "Tempestade leve",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  211: {
    main: "Tempestade",
    description: "Tempestade",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  212: {
    main: "Tempestade",
    description: "Forte tempestade",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  221: {
    main: "Tempestade",
    description: "Tempestade irregular",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  230: {
    main: "Tempestade",
    description: "Trovoadas com garoa leve",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  231: {
    main: "Tempestade",
    description: "Trovoadas com garoa",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },
  232: {
    main: "Tempestade",
    description: "Trovoadas fortes com garoa",
    iconDay: "wi-day-thunderstorm",
    iconNight: "wi-night-thunderstorm",
  },

  300: {
    main: "Chuvisco",
    description: "Garoa leve",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  301: {
    main: "Chuvisco",
    description: "Chuvisco",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  302: {
    main: "Chuvisco",
    description: "Garoa forte",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  310: {
    main: "Chuvisco",
    description: "Chuvisco leve com garoa",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  311: {
    main: "Chuvisco",
    description: "Garoa",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  312: {
    main: "Chuvisco",
    description: "Chuva forte com garoa",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  313: {
    main: "Chuvisco",
    description: "Chuva e garoa",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  314: {
    main: "Chuvisco",
    description: "Chuva forte e garoa",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },
  321: {
    main: "Chuvisco",
    description: "Chuvisco",
    iconDay: "wi-day-sprinkle",
    iconNight: "wi-night-alt-sprinkle",
  },

  500: {
    main: "Chuva",
    description: "Chuva leve",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  501: {
    main: "Chuva",
    description: "chuva moderada",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  502: {
    main: "Chuva",
    description: "Chuva muito forte",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  503: {
    main: "Chuva",
    description: "Chuva muito forte",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  504: {
    main: "Chuva",
    description: "Chuva extrema",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  511: {
    main: "Chuva",
    description: "Chuva congelante",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  520: {
    main: "Chuva",
    description: "Chuva leve",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  521: {
    main: "Chuva",
    description: "Chuva",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  522: {
    main: "Chuva",
    description: "Chuva de forte intensidade",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },
  531: {
    main: "Chuva",
    description: "Chuva irregular",
    iconDay: "wi-day-rain",
    iconNight: "wi-night-alt-rain",
  },

  600: {
    main: "Neve",
    description: "Nevasca fraca",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  601: {
    main: "Neve",
    description: "Neve",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  602: {
    main: "Neve",
    description: "Nevasca forte",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  611: {
    main: "Neve",
    description: "Granizo",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  612: {
    main: "Neve",
    description: "Leve chuva de granizo",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  613: {
    main: "Neve",
    description: "Tempestade de granizo",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  615: {
    main: "Neve",
    description: "Chuva fraca e neve",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  616: {
    main: "Neve",
    description: "Chuva e neve",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  620: {
    main: "Neve",
    description: "Nevasca fraca",
    iconDay: "wi-day-snow",
    iconNight: "wi-night-alt-snow",
  },
  621: {
    main: "Neve",
    description: "Nevasca",
    iconDay: "",
    iconNight: "",
  },
  622: {
    main: "Neve",
    description: "Nevasca forte",
    iconDay: "",
    iconNight: "",
  },

  701: {
    main: "Nevoeiro",
    description: "Nevoeiro",
    iconDay: "wi-smog",
    iconNight: "wi-smog",
  },
  711: {
    main: "Fumaça",
    description: "Fumaça",
    iconDay: "wi-smoke",
    iconNight: "wi-smoke",
  },
  721: {
    main: "Nevoeiro",
    description: "Neblina",
    iconDay: "wi-day-haze",
    iconNight: "wi-day-haze",
  },
  731: {
    main: "Areia",
    description: "Redemoinhos de areia",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  741: {
    main: "Neblina",
    description: "Neblina",
    iconDay: "wi-fog",
    iconNight: "wi-night-fog",
  },
  751: {
    main: "Areia",
    description: "Areia",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  761: {
    main: "Areia",
    description: "Poeira",
    iconDay: "wi-dust",
    iconNight: "wi-dust",
  },
  762: {
    main: "Ash",
    description: "Cinzas vulcânicas",
    iconDay: "wi-volcano",
    iconNight: "wi-volcano",
  },
  771: {
    main: "Rajadas de vento",
    description: "Rajadas de vento",
    iconDay: "wi-strong-wind",
    iconNight: "wi-strong-wind",
  },
  781: {
    main: "Tornado",
    description: "Tornado",
    iconDay: "wi-tornado",
    iconNight: "wi-tornado",
  },

  800: {
    main: "Limpo",
    description: "céu limpo",
    iconDay: "wi-day-sunny",
    iconNight: "wi-night-clear",
  },
  801: {
    main: "Nuvens",
    description: "poucas nuvens",
    iconDay: "wi-day-cloudy",
    iconNight: "wi-night-alt-cloudy",
  },
  802: {
    main: "Nuvens esparças",
    description: "algumas nuvens",
    iconDay: "wi-day-cloudy",
    iconNight: "wi-night-alt-cloudy",
  },
  803: {
    main: "Parcialmente nublado",
    description: "muitas nuvens",
    iconDay: "wi-cloudy",
    iconNight: "wi-cloudy",
  },
  804: {
    main: "Nublado",
    description: "100% nublado",
    iconDay: "wi-cloudy",
    iconNight: "wi-cloudy",
  },
};
